android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false

org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC

# Maven Central coordinates (com.vanniktech.maven.publish)
GROUP=com.verifyblind
POM_ARTIFACT_ID=verifyblind-android
VERSION_NAME=1.0.1
